name: gitaction test

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v2
    - name: Run pwd
      run: pwd
    - name: Run la -al
      run: ls -al
